version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  aws-cli: circleci/aws-cli@2.0.3
# Orchestrate or schedule a set of jobs

commands:
 destroying_infrastructure:
   steps:
    - checkout
    - run:
       name: delete infra on failure
       command: |
         aws cloudformation delete-stack --stack-name my-stack
       when: on_fail
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps: 
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            pwd
            ls -la
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name my-stack
      - run: return 1
      - destroying_infrastructure
       
workflows:
  shine:
    jobs:
       - create_infrastructure
  
